image: python:3.6.4-stretch

tox:
  script:
  - pip install tox
  - tox

pages:
  script:
  - pip install sphinx solar-theme
  - python setup.py install
  - rm -rf docs/source && sphinx-apidoc -e -f -o docs/source/ quart/
  - cd docs/ && make html && cd ../
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
